### ISSUE TITLE
Default up command is not compatible with site:down

### ISSUE THREAD

**Issue by rdarcy1** [konsulting/laravel-maintenance-mode#1]
After calling `site:down`, `php artisan up` doesn't seem to bring the site back up.

Should either make this method compatible when using the file driver, or override the default illuminate commands.

**Comment by Keoghan** [comment]
I think you need site:up but yeah, it would be better to override the default commands up and down instead of introducing more.

On 4 Sep 2018, at 18:28, rdarcy1 <notifications@github.com> wrote:

After calling site:down, php artisan up doesn't seem to bring the site back up.

Should either make this method compatible when using the file driver, or override the default illuminate commands.

**Comment by rdarcy1** [comment]
Resolved in 01baa915f62f2fee93bedd6305bcea448fc9d6dc
